services:
 api-montvenue-pg:
  image: bitnami/postgresql:latest
  ports:
   - 5432:5432
  environment:
   - POSTGRESQL_PASSWORD=docker
   - POSTGRESQL_USERNAME=docker
   - POSTGRESQL_DATABASE=montvenue
